#!/usr/bin/env python3
"""Generate the app's market snapshot from canonical model artifacts."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from nba_stock_market.backtest import normalize_player_name


DEFAULT_OPENINGS = ROOT / "output/opening-prices-2026-27.csv"
DEFAULT_BACKTEST = ROOT / "output/backtest-2026.json"
DEFAULT_GAME_LOG = ROOT / "data/raw/2025-26/player_game_logs.csv"
DEFAULT_OUTPUT = ROOT / "app/src/data/snapshot.ts"

DEMO_RIVALS = (
    (1, "portfolio-048", 168_604_261, 20.43),
    (2, "Buckets & Bonds", 161_280_440, 15.2),
    (3, "The Sixth Trader", 156_890_020, 12.06),
    (4, "Midrange Capital", 151_422_700, 8.16),
)


def _canonical_players(game_log: Path) -> dict[str, tuple[str, str]]:
    identities: defaultdict[str, Counter[tuple[str, str]]] = defaultdict(Counter)
    with game_log.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            name = row["player_name"].strip()
            identities[normalize_player_name(name)][(row["player_id"], name)] += 1
    return {key: counts.most_common(1)[0][0] for key, counts in identities.items()}


def _load_players(openings: Path, game_log: Path, limit: int) -> list[dict[str, Any]]:
    if limit <= 0:
        raise ValueError("player limit must be positive")
    identities = _canonical_players(game_log)
    players: list[dict[str, Any]] = []
    with openings.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if len(players) >= limit:
                break
            key = normalize_player_name(row["player"])
            if key not in identities:
                raise ValueError(f"no canonical player id for {row['player']}")
            player_id, canonical_name = identities[key]
            players.append(
                {
                    "id": player_id,
                    "name": canonical_name,
                    "tier": row["tier"],
                    "listing_price": round(float(row["opening_price"])),
                    "actual_salary": round(float(row["actual_salary"])),
                }
            )
    if len(players) != limit:
        raise ValueError(f"expected {limit} opening-price players, found {len(players)}")
    return players


def _load_dividend_events(
    backtest: Path,
    players: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    report = json.loads(backtest.read_text(encoding="utf-8"))
    ids = {normalize_player_name(player["name"]): player["id"] for player in players}
    events = []
    for example in report["examples"]:
        player_id = ids.get(normalize_player_name(example["player"]))
        if player_id is None:
            continue
        events.append(
            {
                "player_id": player_id,
                "game_date": example["game_date"],
                "actual_net_points": example["actual_net_points"],
                "expected_net_points": example["expected_net_points"],
                "dividend_per_holder": example["payout_per_share"],
            }
        )
    if not events:
        raise ValueError("backtest examples do not include any app snapshot player")
    return events


def _render_object(row: dict[str, Any]) -> str:
    parts = []
    for key, value in row.items():
        rendered = json.dumps(value, ensure_ascii=False) if isinstance(value, str) else str(value)
        parts.append(f"{key}: {rendered}")
    return "{ " + ", ".join(parts) + " }"


def render_snapshot(players: list[dict[str, Any]], events: list[dict[str, Any]]) -> str:
    lines = [
        "import type { DividendEvent, Player } from './types';",
        "",
        "// Generated by scripts/generate_app_snapshot.py from the canonical opening-price",
        "// CSV and backtest JSON. Do not edit the market data by hand.",
        "export const players: Player[] = [",
    ]
    lines.extend(f"  {_render_object(player)}," for player in players)
    lines.extend([
        "];",
        "",
        "export const dividendEvents: DividendEvent[] = [",
    ])
    lines.extend(f"  {_render_object(event)}," for event in events)
    lines.extend([
        "];",
        "",
        "// Demo opponents until the multiplayer leaderboard API is wired.",
        "export const leaderboardRivals = [",
    ])
    for rank, name, value, return_pct in DEMO_RIVALS:
        lines.append(
            f"  {{ rank: {rank}, name: {json.dumps(name)}, value: {value}, returnPct: {return_pct} }},"
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def generate_snapshot(
    openings: Path = DEFAULT_OPENINGS,
    backtest: Path = DEFAULT_BACKTEST,
    game_log: Path = DEFAULT_GAME_LOG,
    *,
    limit: int = 30,
) -> str:
    players = _load_players(openings, game_log, limit)
    events = _load_dividend_events(backtest, players)
    return render_snapshot(players, events)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--openings", type=Path, default=DEFAULT_OPENINGS)
    parser.add_argument("--backtest", type=Path, default=DEFAULT_BACKTEST)
    parser.add_argument("--game-log", type=Path, default=DEFAULT_GAME_LOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--limit", type=int, default=30)
    args = parser.parse_args(argv)

    rendered = generate_snapshot(
        args.openings,
        args.backtest,
        args.game_log,
        limit=args.limit,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
