#!/usr/bin/env python3
"""Generate deterministic app trend series from committed 2025-26 caches."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from nba_stock_market.engine import (
    NET_POINTS_TO_DOLLARS,
    SHARES_OUT,
    BoxScoreLine,
    NetPointsModel,
    Player,
)
from nba_stock_market.expectations import (
    DunksAndThreesExpectation,
    player_salary_implied_net_points,
)
from nba_stock_market.historical_data import load_game_records


GAME_LOG = ROOT / "data/raw/2025-26/player_game_logs.csv"
DNT_CACHE = ROOT / "data/raw/dnt"
SNAPSHOT = ROOT / "app/src/data/snapshot.ts"
DEFAULT_OUTPUT = ROOT / "app/src/data/trends.ts"
MIN_GAME_COUNT = 15
PER_HOLDER_DOLLARS_PER_NP = NET_POINTS_TO_DOLLARS / SHARES_OUT

SNAPSHOT_PLAYER = re.compile(
    r"\{ id: '([^']+)', name: '([^']+)', tier: '([^']+)', "
    r"listing_price: ([\d_]+), actual_salary: ([\d_]+) \}"
)


def _snapshot_players(path: Path = SNAPSHOT) -> list[Player]:
    players: list[Player] = []
    for match in SNAPSHOT_PLAYER.finditer(path.read_text(encoding="utf-8")):
        player_id, name, tier, price, salary = match.groups()
        listing_price = float(price.replace("_", ""))
        players.append(
            Player(
                player_id,
                name,
                tier,
                listing_price,
                listing_price,
                actual_salary=float(salary.replace("_", "")),
            )
        )
    if len(players) != 30:
        raise ValueError(f"expected 30 snapshot players, found {len(players)} in {path}")
    return players


def _rounded(value: float, digits: int) -> float:
    rounded = round(value, digits)
    return 0.0 if rounded == 0 else rounded


def generate() -> dict[str, Any]:
    if PER_HOLDER_DOLLARS_PER_NP != 40_000:
        raise ValueError(
            "engine dividend constants no longer implement the required $40K/NP holder rule"
        )

    players = _snapshot_players()
    player_by_id = {player.id: player for player in players}
    games_by_player: defaultdict[str, list[Any]] = defaultdict(list)
    for game in load_game_records(GAME_LOG):
        if game.player_id in player_by_id:
            games_by_player[game.player_id].append(game)

    net_points = NetPointsModel()
    expectations = DunksAndThreesExpectation(cache_dir=DNT_CACHE)

    def point(player: Player, game: Any) -> dict[str, float | str]:
        np = net_points.score(game.box_score)
        projected = expectations.expected_performance(player, game.game_date)
        expected_np = (
            player_salary_implied_net_points(player)
            if projected is None
            else net_points.score(projected)
            if isinstance(projected, BoxScoreLine)
            else float(projected)
        )
        return {
            "date": game.game_date.isoformat(),
            "np": _rounded(np, 5),
            "expected_np": _rounded(expected_np, 5),
            "dividend_per_holder": _rounded(
                (np - expected_np) * PER_HOLDER_DOLLARS_PER_NP, 2
            ),
        }

    trends: dict[str, list[dict[str, float | str]]] = {}
    for player in players:
        games = sorted(
            games_by_player[player.id],
            key=lambda game: (game.game_date, game.game_id),
        )
        if len(games) < MIN_GAME_COUNT:
            raise ValueError(
                f"{player.name} has only {len(games)} cached games; need {MIN_GAME_COUNT}"
            )
        trends[player.id] = [point(player, game) for game in games]

    jokic = player_by_id["3112335"]
    christmas = next(
        game
        for game in games_by_player[jokic.id]
        if game.game_date.isoformat() == "2025-12-25"
    )
    return {
        "player_trends": trends,
        "spot_checks": {jokic.id: {"2025-12-25": point(jokic, christmas)}},
    }


def render_typescript(generated: dict[str, Any]) -> str:
    trends = json.dumps(generated["player_trends"], indent=2, ensure_ascii=False)
    spot_checks = json.dumps(generated["spot_checks"], indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_app_trends.py from committed ESPN and D&T caches.\n"
        "// Do not edit by hand.\n\n"
        "export interface TrendPoint {\n"
        "  date: string;\n"
        "  np: number;\n"
        "  expected_np: number;\n"
        "  dividend_per_holder: number;\n"
        "}\n\n"
        f"export const playerTrends: Record<string, TrendPoint[]> = {trends};\n\n"
        "// A stable source-data spot check retained alongside the full-season series.\n"
        "export const trendSpotChecks: Record<string, Record<string, TrendPoint>> = "
        f"{spot_checks};\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--json-output", type=Path)
    args = parser.parse_args(argv)

    generated = generate()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_typescript(generated), encoding="utf-8")
    if args.json_output is not None:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(
            json.dumps(generated, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
