import type { DividendEvent, Player } from './types';

// Generated by scripts/generate_app_snapshot.py from the canonical opening-price
// CSV and backtest JSON. Do not edit the market data by hand.
export const players: Player[] = [
  { id: "3112335", name: "Nikola Jokic", tier: "star", listing_price: 51668326, actual_salary: 59033114 },
  { id: "4278073", name: "Shai Gilgeous-Alexander", tier: "star", listing_price: 50355233, actual_salary: 40806150 },
  { id: "5104157", name: "Victor Wembanyama", tier: "star", listing_price: 47134433, actual_salary: 16868246 },
  { id: "3945274", name: "Luka Doncic", tier: "star", listing_price: 47012753, actual_salary: 48967380 },
  { id: "6450", name: "Kawhi Leonard", tier: "star", listing_price: 42626287, actual_salary: 50300000 },
  { id: "4432166", name: "Cade Cunningham", tier: "star", listing_price: 40898711, actual_salary: 50105628 },
  { id: "3078576", name: "Derrick White", tier: "star", listing_price: 39195457, actual_salary: 30348000 },
  { id: "3908809", name: "Donovan Mitchell", tier: "star", listing_price: 37272093, actual_salary: 50105628 },
  { id: "4066261", name: "Bam Adebayo", tier: "star", listing_price: 37139279, actual_salary: 51033600 },
  { id: "4433255", name: "Chet Holmgren", tier: "star", listing_price: 37010478, actual_salary: 13731368 },
  { id: "4431678", name: "Tyrese Maxey", tier: "star", listing_price: 36175018, actual_salary: 40770520 },
  { id: "4433134", name: "Scottie Barnes", tier: "star", listing_price: 36039160, actual_salary: 41754636 },
  { id: "3136195", name: "Karl-Anthony Towns", tier: "star", listing_price: 35012927, actual_salary: 57078728 },
  { id: "4432816", name: "LaMelo Ball", tier: "star", listing_price: 34542883, actual_salary: 40770520 },
  { id: "4684740", name: "Amen Thompson", tier: "star", listing_price: 34265074, actual_salary: 12258609 },
  { id: "3202", name: "Kevin Durant", tier: "star", listing_price: 34170043, actual_salary: 54708609 },
  { id: "3136193", name: "Devin Booker", tier: "star", listing_price: 33011461, actual_salary: 57078728 },
  { id: "3032977", name: "Giannis Antetokounmpo", tier: "star", listing_price: 32235775, actual_salary: 58456490 },
  { id: "4869342", name: "Dyson Daniels", tier: "star", listing_price: 31729461, actual_salary: 7707709 },
  { id: "4432158", name: "Evan Mobley", tier: "star", listing_price: 31632044, actual_salary: 50105628 },
  { id: "3936299", name: "Jamal Murray", tier: "star", listing_price: 31348812, actual_salary: 50105628 },
  { id: "4433621", name: "Jalen Duren", tier: "star", listing_price: 31316192, actual_salary: 6483144 },
  { id: "3934672", name: "Jalen Brunson", tier: "star", listing_price: 31070645, actual_salary: 37739521 },
  { id: "4066320", name: "Desmond Bane", tier: "star", listing_price: 30310277, actual_salary: 39446090 },
  { id: "5105565", name: "Donovan Clingan", tier: "mid", listing_price: 29486091, actual_salary: 7519920 },
  { id: "3917376", name: "Jaylen Brown", tier: "mid", listing_price: 29205835, actual_salary: 57078728 },
  { id: "5061575", name: "Kon Knueppel", tier: "mid", listing_price: 28960025, actual_salary: 0 },
  { id: "4066259", name: "De'Aaron Fox", tier: "mid", listing_price: 28376936, actual_salary: 37096620 },
  { id: "3934719", name: "OG Anunoby", tier: "mid", listing_price: 28291963, actual_salary: 42500000 },
  { id: "4278585", name: "Collin Gillespie", tier: "mid", listing_price: 28152210, actual_salary: 0 },
];

export const dividendEvents: DividendEvent[] = [
  { player_id: "4278073", game_date: "2025-10-23", actual_net_points: 43.6, expected_net_points: 23.2488, dividend_per_holder: 814049.8 },
  { player_id: "3112335", game_date: "2025-12-25", actual_net_points: 59.35, expected_net_points: 25.9831, dividend_per_holder: 1334675.2 },
  { player_id: "3945274", game_date: "2026-03-19", actual_net_points: 54.45, expected_net_points: 25.063, dividend_per_holder: 1175480.8 },
];

// Demo opponents until the multiplayer leaderboard API is wired.
export const leaderboardRivals = [
  { rank: 1, name: "portfolio-048", value: 168604261, returnPct: 20.43 },
  { rank: 2, name: "Buckets & Bonds", value: 161280440, returnPct: 15.2 },
  { rank: 3, name: "The Sixth Trader", value: 156890020, returnPct: 12.06 },
  { rank: 4, name: "Midrange Capital", value: 151422700, returnPct: 8.16 },
];
