// Generated by scripts/generate_app_trends.py from committed ESPN and D&T caches.
// Do not edit by hand.

export interface TrendPoint {
  date: string;
  np: number;
  expected_np: number;
  dividend_per_holder: number;
}

export const playerTrends: Record<string, TrendPoint[]> = {
  "3112335": [
    {
      "date": "2026-03-12",
      "np": 38.55,
      "expected_np": 25.33112,
      "dividend_per_holder": 528755.4
    },
    {
      "date": "2026-03-14",
      "np": 31.05,
      "expected_np": 27.57094,
      "dividend_per_holder": 139162.6
    },
    {
      "date": "2026-03-17",
      "np": 9.0,
      "expected_np": 28.66934,
      "dividend_per_holder": -786773.4
    },
    {
      "date": "2026-03-18",
      "np": 22.15,
      "expected_np": 25.05027,
      "dividend_per_holder": -116010.8
    },
    {
      "date": "2026-03-20",
      "np": 22.15,
      "expected_np": 25.39161,
      "dividend_per_holder": -129664.4
    },
    {
      "date": "2026-03-22",
      "np": 25.15,
      "expected_np": 26.58754,
      "dividend_per_holder": -57501.6
    },
    {
      "date": "2026-03-24",
      "np": 28.2,
      "expected_np": 24.60057,
      "dividend_per_holder": 143977.0
    },
    {
      "date": "2026-03-25",
      "np": 30.35,
      "expected_np": 26.98827,
      "dividend_per_holder": 134469.2
    },
    {
      "date": "2026-03-27",
      "np": 32.95,
      "expected_np": 29.27542,
      "dividend_per_holder": 146983.2
    },
    {
      "date": "2026-03-29",
      "np": 23.4,
      "expected_np": 27.52221,
      "dividend_per_holder": -164888.2
    },
    {
      "date": "2026-04-01",
      "np": 14.2,
      "expected_np": 28.35437,
      "dividend_per_holder": -566174.8
    },
    {
      "date": "2026-04-04",
      "np": 38.95,
      "expected_np": 24.17204,
      "dividend_per_holder": 591118.4
    },
    {
      "date": "2026-04-06",
      "np": 36.8,
      "expected_np": 27.89416,
      "dividend_per_holder": 356233.6
    },
    {
      "date": "2026-04-08",
      "np": 21.2,
      "expected_np": 30.04969,
      "dividend_per_holder": -353987.8
    },
    {
      "date": "2026-04-12",
      "np": 22.5,
      "expected_np": 24.03223,
      "dividend_per_holder": -61289.0
    }
  ],
  "4278073": [
    {
      "date": "2026-03-09",
      "np": 40.3,
      "expected_np": 24.90933,
      "dividend_per_holder": 615626.8
    },
    {
      "date": "2026-03-12",
      "np": 35.7,
      "expected_np": 24.79313,
      "dividend_per_holder": 436274.8
    },
    {
      "date": "2026-03-15",
      "np": 15.45,
      "expected_np": 26.87899,
      "dividend_per_holder": -457159.6
    },
    {
      "date": "2026-03-17",
      "np": 30.65,
      "expected_np": 25.03052,
      "dividend_per_holder": 224779.4
    },
    {
      "date": "2026-03-18",
      "np": 25.0,
      "expected_np": 26.15691,
      "dividend_per_holder": -46276.6
    },
    {
      "date": "2026-03-21",
      "np": 31.7,
      "expected_np": 24.99609,
      "dividend_per_holder": 268156.4
    },
    {
      "date": "2026-03-23",
      "np": 18.25,
      "expected_np": 23.76389,
      "dividend_per_holder": -220555.4
    },
    {
      "date": "2026-03-25",
      "np": 32.55,
      "expected_np": 20.0104,
      "dividend_per_holder": 501584.2
    },
    {
      "date": "2026-03-27",
      "np": 13.85,
      "expected_np": 25.45663,
      "dividend_per_holder": -464265.0
    },
    {
      "date": "2026-03-29",
      "np": 17.8,
      "expected_np": 22.47353,
      "dividend_per_holder": -186941.2
    },
    {
      "date": "2026-03-30",
      "np": 37.8,
      "expected_np": 22.93787,
      "dividend_per_holder": 594485.2
    },
    {
      "date": "2026-04-02",
      "np": 21.1,
      "expected_np": 24.88361,
      "dividend_per_holder": -151344.6
    },
    {
      "date": "2026-04-05",
      "np": 18.55,
      "expected_np": 26.39175,
      "dividend_per_holder": -313669.8
    },
    {
      "date": "2026-04-07",
      "np": 23.7,
      "expected_np": 21.98702,
      "dividend_per_holder": 68519.2
    },
    {
      "date": "2026-04-08",
      "np": 16.9,
      "expected_np": 19.98035,
      "dividend_per_holder": -123214.2
    }
  ],
  "4432166": [
    {
      "date": "2026-02-23",
      "np": 7.6,
      "expected_np": 19.61066,
      "dividend_per_holder": -480426.4
    },
    {
      "date": "2026-02-25",
      "np": 29.65,
      "expected_np": 19.71071,
      "dividend_per_holder": 397571.6
    },
    {
      "date": "2026-02-27",
      "np": 19.2,
      "expected_np": 21.56536,
      "dividend_per_holder": -94614.4
    },
    {
      "date": "2026-03-01",
      "np": 20.5,
      "expected_np": 20.10045,
      "dividend_per_holder": 15982.0
    },
    {
      "date": "2026-03-03",
      "np": 4.7,
      "expected_np": 20.71368,
      "dividend_per_holder": -640547.4
    },
    {
      "date": "2026-03-05",
      "np": 11.8,
      "expected_np": 20.17344,
      "dividend_per_holder": -334937.4
    },
    {
      "date": "2026-03-08",
      "np": 17.9,
      "expected_np": 21.21663,
      "dividend_per_holder": -132665.2
    },
    {
      "date": "2026-03-10",
      "np": 26.35,
      "expected_np": 21.17722,
      "dividend_per_holder": 206911.4
    },
    {
      "date": "2026-03-12",
      "np": 12.2,
      "expected_np": 18.88355,
      "dividend_per_holder": -267342.0
    },
    {
      "date": "2026-03-13",
      "np": 23.8,
      "expected_np": 18.72993,
      "dividend_per_holder": 202802.8
    },
    {
      "date": "2026-03-15",
      "np": 25.05,
      "expected_np": 16.39535,
      "dividend_per_holder": 346185.8
    },
    {
      "date": "2026-03-17",
      "np": 5.6,
      "expected_np": 20.33203,
      "dividend_per_holder": -589281.0
    },
    {
      "date": "2026-04-08",
      "np": 13.6,
      "expected_np": 11.43099,
      "dividend_per_holder": 86760.4
    },
    {
      "date": "2026-04-10",
      "np": 10.85,
      "expected_np": 10.66954,
      "dividend_per_holder": 7218.2
    },
    {
      "date": "2026-04-12",
      "np": 5.8,
      "expected_np": 15.51352,
      "dividend_per_holder": -388540.6
    }
  ],
  "5104157": [
    {
      "date": "2026-03-08",
      "np": 31.75,
      "expected_np": 19.84313,
      "dividend_per_holder": 476274.8
    },
    {
      "date": "2026-03-10",
      "np": 29.7,
      "expected_np": 19.95597,
      "dividend_per_holder": 389761.2
    },
    {
      "date": "2026-03-14",
      "np": 34.25,
      "expected_np": 21.76248,
      "dividend_per_holder": 499500.8
    },
    {
      "date": "2026-03-16",
      "np": 15.35,
      "expected_np": 21.62374,
      "dividend_per_holder": -250949.8
    },
    {
      "date": "2026-03-17",
      "np": 15.15,
      "expected_np": 23.29762,
      "dividend_per_holder": -325904.8
    },
    {
      "date": "2026-03-19",
      "np": 29.2,
      "expected_np": 20.55844,
      "dividend_per_holder": 345662.4
    },
    {
      "date": "2026-03-21",
      "np": 20.9,
      "expected_np": 23.90422,
      "dividend_per_holder": -120168.8
    },
    {
      "date": "2026-03-23",
      "np": 25.65,
      "expected_np": 19.5442,
      "dividend_per_holder": 244232.0
    },
    {
      "date": "2026-03-25",
      "np": 28.1,
      "expected_np": 22.23956,
      "dividend_per_holder": 234417.6
    },
    {
      "date": "2026-03-28",
      "np": 19.3,
      "expected_np": 19.8224,
      "dividend_per_holder": -20896.2
    },
    {
      "date": "2026-03-30",
      "np": 41.85,
      "expected_np": 23.71124,
      "dividend_per_holder": 725550.4
    },
    {
      "date": "2026-04-01",
      "np": 42.45,
      "expected_np": 23.45654,
      "dividend_per_holder": 759738.4
    },
    {
      "date": "2026-04-04",
      "np": 37.8,
      "expected_np": 22.62701,
      "dividend_per_holder": 606919.8
    },
    {
      "date": "2026-04-06",
      "np": 14.15,
      "expected_np": 25.20259,
      "dividend_per_holder": -442103.8
    },
    {
      "date": "2026-04-10",
      "np": 39.35,
      "expected_np": 21.95473,
      "dividend_per_holder": 695811.0
    }
  ],
  "3945274": [
    {
      "date": "2026-03-05",
      "np": 22.5,
      "expected_np": 21.46785,
      "dividend_per_holder": 41285.8
    },
    {
      "date": "2026-03-06",
      "np": 40.8,
      "expected_np": 24.89483,
      "dividend_per_holder": 636206.6
    },
    {
      "date": "2026-03-08",
      "np": 20.6,
      "expected_np": 22.34815,
      "dividend_per_holder": -69926.2
    },
    {
      "date": "2026-03-10",
      "np": 27.05,
      "expected_np": 23.57493,
      "dividend_per_holder": 139002.8
    },
    {
      "date": "2026-03-12",
      "np": 49.25,
      "expected_np": 24.69937,
      "dividend_per_holder": 982025.4
    },
    {
      "date": "2026-03-14",
      "np": 21.75,
      "expected_np": 24.4988,
      "dividend_per_holder": -109952.0
    },
    {
      "date": "2026-03-16",
      "np": 23.9,
      "expected_np": 23.26365,
      "dividend_per_holder": 25454.0
    },
    {
      "date": "2026-03-18",
      "np": 29.25,
      "expected_np": 23.26859,
      "dividend_per_holder": 239256.6
    },
    {
      "date": "2026-03-19",
      "np": 54.45,
      "expected_np": 24.62711,
      "dividend_per_holder": 1192915.4
    },
    {
      "date": "2026-03-21",
      "np": 23.65,
      "expected_np": 24.88558,
      "dividend_per_holder": -49423.0
    },
    {
      "date": "2026-03-23",
      "np": 21.0,
      "expected_np": 23.97122,
      "dividend_per_holder": -118848.6
    },
    {
      "date": "2026-03-25",
      "np": 29.85,
      "expected_np": 27.08079,
      "dividend_per_holder": 110768.6
    },
    {
      "date": "2026-03-27",
      "np": 33.95,
      "expected_np": 27.68979,
      "dividend_per_holder": 250408.4
    },
    {
      "date": "2026-03-31",
      "np": 40.65,
      "expected_np": 26.4857,
      "dividend_per_holder": 566572.0
    },
    {
      "date": "2026-04-02",
      "np": 4.15,
      "expected_np": 22.73017,
      "dividend_per_holder": -743206.8
    }
  ],
  "3032977": [
    {
      "date": "2026-01-04",
      "np": 30.8,
      "expected_np": 22.05845,
      "dividend_per_holder": 349662.2
    },
    {
      "date": "2026-01-07",
      "np": 27.75,
      "expected_np": 21.92731,
      "dividend_per_holder": 232907.8
    },
    {
      "date": "2026-01-09",
      "np": 22.45,
      "expected_np": 23.21826,
      "dividend_per_holder": -30730.4
    },
    {
      "date": "2026-01-11",
      "np": 31.5,
      "expected_np": 22.44146,
      "dividend_per_holder": 362341.6
    },
    {
      "date": "2026-01-13",
      "np": 15.1,
      "expected_np": 23.63496,
      "dividend_per_holder": -341398.2
    },
    {
      "date": "2026-01-15",
      "np": 16.05,
      "expected_np": 22.23682,
      "dividend_per_holder": -247472.8
    },
    {
      "date": "2026-01-19",
      "np": 20.95,
      "expected_np": 21.28158,
      "dividend_per_holder": -13263.2
    },
    {
      "date": "2026-01-21",
      "np": 19.45,
      "expected_np": 21.11002,
      "dividend_per_holder": -66400.8
    },
    {
      "date": "2026-01-23",
      "np": 18.8,
      "expected_np": 23.05892,
      "dividend_per_holder": -170357.0
    },
    {
      "date": "2026-03-02",
      "np": 10.95,
      "expected_np": 19.61009,
      "dividend_per_holder": -346403.6
    },
    {
      "date": "2026-03-04",
      "np": 19.2,
      "expected_np": 21.29228,
      "dividend_per_holder": -83691.4
    },
    {
      "date": "2026-03-07",
      "np": 29.65,
      "expected_np": 22.1207,
      "dividend_per_holder": 301172.0
    },
    {
      "date": "2026-03-10",
      "np": 12.55,
      "expected_np": 20.43445,
      "dividend_per_holder": -315377.8
    },
    {
      "date": "2026-03-12",
      "np": 19.95,
      "expected_np": 18.00973,
      "dividend_per_holder": 77610.8
    },
    {
      "date": "2026-03-15",
      "np": 29.45,
      "expected_np": 23.77655,
      "dividend_per_holder": 226937.8
    }
  ],
  "6450": [
    {
      "date": "2026-03-11",
      "np": 43.85,
      "expected_np": 22.39215,
      "dividend_per_holder": 858313.8
    },
    {
      "date": "2026-03-13",
      "np": 15.95,
      "expected_np": 24.7763,
      "dividend_per_holder": -353052.2
    },
    {
      "date": "2026-03-14",
      "np": 21.4,
      "expected_np": 24.3481,
      "dividend_per_holder": -117923.8
    },
    {
      "date": "2026-03-18",
      "np": 20.75,
      "expected_np": 22.92116,
      "dividend_per_holder": -86846.6
    },
    {
      "date": "2026-03-21",
      "np": 28.45,
      "expected_np": 20.84297,
      "dividend_per_holder": 304281.2
    },
    {
      "date": "2026-03-23",
      "np": 24.15,
      "expected_np": 22.26964,
      "dividend_per_holder": 75214.2
    },
    {
      "date": "2026-03-25",
      "np": 16.6,
      "expected_np": 19.42906,
      "dividend_per_holder": -113162.4
    },
    {
      "date": "2026-03-27",
      "np": 23.55,
      "expected_np": 20.2935,
      "dividend_per_holder": 130260.2
    },
    {
      "date": "2026-03-29",
      "np": 16.5,
      "expected_np": 22.3681,
      "dividend_per_holder": -234724.2
    },
    {
      "date": "2026-03-31",
      "np": 15.75,
      "expected_np": 20.24362,
      "dividend_per_holder": -179744.6
    },
    {
      "date": "2026-04-02",
      "np": 23.85,
      "expected_np": 20.66131,
      "dividend_per_holder": 127547.6
    },
    {
      "date": "2026-04-05",
      "np": 18.35,
      "expected_np": 21.79503,
      "dividend_per_holder": -137801.4
    },
    {
      "date": "2026-04-07",
      "np": 25.0,
      "expected_np": 22.29085,
      "dividend_per_holder": 108366.2
    },
    {
      "date": "2026-04-08",
      "np": 11.05,
      "expected_np": 19.69721,
      "dividend_per_holder": -345888.6
    },
    {
      "date": "2026-04-10",
      "np": 18.9,
      "expected_np": 20.29328,
      "dividend_per_holder": -55731.2
    }
  ],
  "3975": [
    {
      "date": "2026-01-09",
      "np": 23.0,
      "expected_np": 20.30564,
      "dividend_per_holder": 107774.6
    },
    {
      "date": "2026-01-11",
      "np": 20.2,
      "expected_np": 19.16101,
      "dividend_per_holder": 41559.6
    },
    {
      "date": "2026-01-13",
      "np": 7.55,
      "expected_np": 19.35638,
      "dividend_per_holder": -472255.4
    },
    {
      "date": "2026-01-15",
      "np": 22.25,
      "expected_np": 17.82528,
      "dividend_per_holder": 176988.8
    },
    {
      "date": "2026-01-17",
      "np": 6.9,
      "expected_np": 18.49661,
      "dividend_per_holder": -463864.2
    },
    {
      "date": "2026-01-19",
      "np": 15.5,
      "expected_np": 17.93074,
      "dividend_per_holder": -97229.8
    },
    {
      "date": "2026-01-20",
      "np": 8.2,
      "expected_np": 16.57761,
      "dividend_per_holder": -335104.4
    },
    {
      "date": "2026-01-22",
      "np": 23.75,
      "expected_np": 15.86298,
      "dividend_per_holder": 315481.0
    },
    {
      "date": "2026-01-25",
      "np": 23.8,
      "expected_np": 16.94103,
      "dividend_per_holder": 274358.6
    },
    {
      "date": "2026-01-28",
      "np": 17.1,
      "expected_np": 17.73258,
      "dividend_per_holder": -25303.0
    },
    {
      "date": "2026-01-30",
      "np": 11.55,
      "expected_np": 16.45754,
      "dividend_per_holder": -196301.6
    },
    {
      "date": "2026-04-05",
      "np": 21.6,
      "expected_np": 14.0284,
      "dividend_per_holder": 302863.8
    },
    {
      "date": "2026-04-07",
      "np": 10.0,
      "expected_np": 18.24392,
      "dividend_per_holder": -329756.6
    },
    {
      "date": "2026-04-10",
      "np": 7.75,
      "expected_np": 14.28434,
      "dividend_per_holder": -261373.4
    },
    {
      "date": "2026-04-12",
      "np": 17.3,
      "expected_np": 12.49893,
      "dividend_per_holder": 192043.0
    }
  ],
  "4066261": [
    {
      "date": "2026-03-12",
      "np": 9.0,
      "expected_np": 21.97299,
      "dividend_per_holder": -518919.4
    },
    {
      "date": "2026-03-14",
      "np": 15.45,
      "expected_np": 20.42711,
      "dividend_per_holder": -199084.2
    },
    {
      "date": "2026-03-19",
      "np": 20.7,
      "expected_np": 20.81509,
      "dividend_per_holder": -4603.6
    },
    {
      "date": "2026-03-21",
      "np": 31.25,
      "expected_np": 18.74996,
      "dividend_per_holder": 500001.6
    },
    {
      "date": "2026-03-23",
      "np": 10.15,
      "expected_np": 20.56061,
      "dividend_per_holder": -416424.6
    },
    {
      "date": "2026-03-25",
      "np": 12.5,
      "expected_np": 18.32145,
      "dividend_per_holder": -232858.0
    },
    {
      "date": "2026-03-27",
      "np": 8.75,
      "expected_np": 17.50792,
      "dividend_per_holder": -350316.8
    },
    {
      "date": "2026-03-29",
      "np": 8.2,
      "expected_np": 18.62564,
      "dividend_per_holder": -417025.8
    },
    {
      "date": "2026-03-30",
      "np": 22.1,
      "expected_np": 17.53883,
      "dividend_per_holder": 182447.0
    },
    {
      "date": "2026-04-01",
      "np": 20.0,
      "expected_np": 16.99506,
      "dividend_per_holder": 120197.6
    },
    {
      "date": "2026-04-04",
      "np": 15.0,
      "expected_np": 20.76648,
      "dividend_per_holder": -230659.4
    },
    {
      "date": "2026-04-07",
      "np": 0.2,
      "expected_np": 14.84601,
      "dividend_per_holder": -585840.6
    },
    {
      "date": "2026-04-09",
      "np": 26.55,
      "expected_np": 15.44042,
      "dividend_per_holder": 444383.2
    },
    {
      "date": "2026-04-10",
      "np": 18.8,
      "expected_np": 18.66461,
      "dividend_per_holder": 5415.6
    },
    {
      "date": "2026-04-12",
      "np": 27.25,
      "expected_np": 17.33563,
      "dividend_per_holder": 396574.6
    }
  ],
  "3136195": [
    {
      "date": "2026-03-08",
      "np": 20.55,
      "expected_np": 13.96352,
      "dividend_per_holder": 263459.4
    },
    {
      "date": "2026-03-09",
      "np": 33.4,
      "expected_np": 14.57278,
      "dividend_per_holder": 753089.0
    },
    {
      "date": "2026-03-11",
      "np": 18.0,
      "expected_np": 17.57499,
      "dividend_per_holder": 17000.6
    },
    {
      "date": "2026-03-15",
      "np": 14.85,
      "expected_np": 16.02329,
      "dividend_per_holder": -46931.6
    },
    {
      "date": "2026-03-17",
      "np": 19.45,
      "expected_np": 17.45619,
      "dividend_per_holder": 79752.4
    },
    {
      "date": "2026-03-20",
      "np": 19.6,
      "expected_np": 16.51136,
      "dividend_per_holder": 123545.6
    },
    {
      "date": "2026-03-22",
      "np": 27.3,
      "expected_np": 18.19846,
      "dividend_per_holder": 364061.4
    },
    {
      "date": "2026-03-24",
      "np": 15.1,
      "expected_np": 16.56613,
      "dividend_per_holder": -58645.4
    },
    {
      "date": "2026-03-26",
      "np": 8.95,
      "expected_np": 14.11398,
      "dividend_per_holder": -206559.2
    },
    {
      "date": "2026-03-29",
      "np": 14.15,
      "expected_np": 12.25991,
      "dividend_per_holder": 75603.4
    },
    {
      "date": "2026-03-31",
      "np": 13.4,
      "expected_np": 13.48023,
      "dividend_per_holder": -3209.4
    },
    {
      "date": "2026-04-01",
      "np": 19.85,
      "expected_np": 16.69149,
      "dividend_per_holder": 126340.2
    },
    {
      "date": "2026-04-06",
      "np": 23.3,
      "expected_np": 14.77072,
      "dividend_per_holder": 341171.4
    },
    {
      "date": "2026-04-09",
      "np": 16.4,
      "expected_np": 14.72404,
      "dividend_per_holder": 67038.4
    },
    {
      "date": "2026-04-10",
      "np": 20.95,
      "expected_np": 15.9759,
      "dividend_per_holder": 198964.0
    }
  ],
  "3908809": [
    {
      "date": "2026-03-08",
      "np": 26.9,
      "expected_np": 17.73858,
      "dividend_per_holder": 366456.8
    },
    {
      "date": "2026-03-09",
      "np": 15.85,
      "expected_np": 19.45714,
      "dividend_per_holder": -144285.4
    },
    {
      "date": "2026-03-11",
      "np": 13.15,
      "expected_np": 17.8965,
      "dividend_per_holder": -189860.0
    },
    {
      "date": "2026-03-13",
      "np": 23.25,
      "expected_np": 19.99627,
      "dividend_per_holder": 130149.0
    },
    {
      "date": "2026-03-15",
      "np": 20.2,
      "expected_np": 20.19711,
      "dividend_per_holder": 115.8
    },
    {
      "date": "2026-03-17",
      "np": 12.6,
      "expected_np": 20.35473,
      "dividend_per_holder": -310189.0
    },
    {
      "date": "2026-03-21",
      "np": 15.95,
      "expected_np": 20.1046,
      "dividend_per_holder": -166184.0
    },
    {
      "date": "2026-03-24",
      "np": 31.8,
      "expected_np": 20.99134,
      "dividend_per_holder": 432346.4
    },
    {
      "date": "2026-03-25",
      "np": 18.0,
      "expected_np": 20.69549,
      "dividend_per_holder": -107819.6
    },
    {
      "date": "2026-03-27",
      "np": 4.7,
      "expected_np": 20.24265,
      "dividend_per_holder": -621705.8
    },
    {
      "date": "2026-03-30",
      "np": 26.1,
      "expected_np": 20.24042,
      "dividend_per_holder": 234383.2
    },
    {
      "date": "2026-03-31",
      "np": 5.15,
      "expected_np": 18.88677,
      "dividend_per_holder": -549470.8
    },
    {
      "date": "2026-04-02",
      "np": 18.35,
      "expected_np": 16.2478,
      "dividend_per_holder": 84087.8
    },
    {
      "date": "2026-04-05",
      "np": 29.7,
      "expected_np": 19.22632,
      "dividend_per_holder": 418947.0
    },
    {
      "date": "2026-04-08",
      "np": 25.05,
      "expected_np": 18.4666,
      "dividend_per_holder": 263336.0
    }
  ],
  "3078576": [
    {
      "date": "2026-03-10",
      "np": 26.45,
      "expected_np": 13.2333,
      "dividend_per_holder": 528667.8
    },
    {
      "date": "2026-03-14",
      "np": 11.05,
      "expected_np": 18.0118,
      "dividend_per_holder": -278472.0
    },
    {
      "date": "2026-03-16",
      "np": 14.2,
      "expected_np": 15.28513,
      "dividend_per_holder": -43405.0
    },
    {
      "date": "2026-03-18",
      "np": 9.8,
      "expected_np": 14.47169,
      "dividend_per_holder": -186867.8
    },
    {
      "date": "2026-03-20",
      "np": 9.0,
      "expected_np": 13.98467,
      "dividend_per_holder": -199386.8
    },
    {
      "date": "2026-03-22",
      "np": 7.55,
      "expected_np": 14.21974,
      "dividend_per_holder": -266789.6
    },
    {
      "date": "2026-03-25",
      "np": 5.1,
      "expected_np": 13.03854,
      "dividend_per_holder": -317541.8
    },
    {
      "date": "2026-03-27",
      "np": -0.2,
      "expected_np": 14.17817,
      "dividend_per_holder": -575126.6
    },
    {
      "date": "2026-03-30",
      "np": 2.7,
      "expected_np": 13.15001,
      "dividend_per_holder": -418000.2
    },
    {
      "date": "2026-04-01",
      "np": 3.25,
      "expected_np": 13.3432,
      "dividend_per_holder": -403728.2
    },
    {
      "date": "2026-04-03",
      "np": 12.3,
      "expected_np": 12.73951,
      "dividend_per_holder": -17580.2
    },
    {
      "date": "2026-04-05",
      "np": 9.6,
      "expected_np": 11.76131,
      "dividend_per_holder": -86452.2
    },
    {
      "date": "2026-04-07",
      "np": 9.5,
      "expected_np": 11.38057,
      "dividend_per_holder": -75222.8
    },
    {
      "date": "2026-04-09",
      "np": -0.1,
      "expected_np": 10.14391,
      "dividend_per_holder": -409756.6
    },
    {
      "date": "2026-04-10",
      "np": 7.25,
      "expected_np": 11.92814,
      "dividend_per_holder": -187125.6
    }
  ],
  "4432158": [
    {
      "date": "2026-03-11",
      "np": 18.3,
      "expected_np": 13.61634,
      "dividend_per_holder": 187346.6
    },
    {
      "date": "2026-03-13",
      "np": 25.65,
      "expected_np": 15.53732,
      "dividend_per_holder": 404507.4
    },
    {
      "date": "2026-03-15",
      "np": 14.35,
      "expected_np": 15.26319,
      "dividend_per_holder": -36527.6
    },
    {
      "date": "2026-03-17",
      "np": 26.15,
      "expected_np": 15.58152,
      "dividend_per_holder": 422739.2
    },
    {
      "date": "2026-03-19",
      "np": 24.25,
      "expected_np": 17.82008,
      "dividend_per_holder": 257196.6
    },
    {
      "date": "2026-03-21",
      "np": 18.05,
      "expected_np": 18.3258,
      "dividend_per_holder": -11032.2
    },
    {
      "date": "2026-03-24",
      "np": 19.75,
      "expected_np": 17.2725,
      "dividend_per_holder": 99100.0
    },
    {
      "date": "2026-03-25",
      "np": 1.35,
      "expected_np": 17.07751,
      "dividend_per_holder": -629100.2
    },
    {
      "date": "2026-03-27",
      "np": 21.75,
      "expected_np": 16.25826,
      "dividend_per_holder": 219669.8
    },
    {
      "date": "2026-03-30",
      "np": 36.2,
      "expected_np": 17.44608,
      "dividend_per_holder": 750156.6
    },
    {
      "date": "2026-03-31",
      "np": 4.65,
      "expected_np": 16.3385,
      "dividend_per_holder": -467539.8
    },
    {
      "date": "2026-04-02",
      "np": 11.6,
      "expected_np": 13.49676,
      "dividend_per_holder": -75870.2
    },
    {
      "date": "2026-04-06",
      "np": 19.9,
      "expected_np": 16.95463,
      "dividend_per_holder": 117814.8
    },
    {
      "date": "2026-04-08",
      "np": 21.35,
      "expected_np": 12.37586,
      "dividend_per_holder": 358965.8
    },
    {
      "date": "2026-04-10",
      "np": 2.5,
      "expected_np": 16.96267,
      "dividend_per_holder": -578506.8
    }
  ],
  "3136193": [
    {
      "date": "2026-03-12",
      "np": 32.4,
      "expected_np": 19.4519,
      "dividend_per_holder": 517924.2
    },
    {
      "date": "2026-03-13",
      "np": 14.95,
      "expected_np": 18.40055,
      "dividend_per_holder": -138022.2
    },
    {
      "date": "2026-03-16",
      "np": 26.7,
      "expected_np": 17.26841,
      "dividend_per_holder": 377263.8
    },
    {
      "date": "2026-03-17",
      "np": 18.4,
      "expected_np": 19.42786,
      "dividend_per_holder": -41114.2
    },
    {
      "date": "2026-03-19",
      "np": 6.7,
      "expected_np": 19.06095,
      "dividend_per_holder": -494438.0
    },
    {
      "date": "2026-03-21",
      "np": 6.7,
      "expected_np": 21.3838,
      "dividend_per_holder": -587352.2
    },
    {
      "date": "2026-03-22",
      "np": 19.25,
      "expected_np": 19.57335,
      "dividend_per_holder": -12933.8
    },
    {
      "date": "2026-03-24",
      "np": 16.45,
      "expected_np": 18.65895,
      "dividend_per_holder": -88358.2
    },
    {
      "date": "2026-03-28",
      "np": 25.6,
      "expected_np": 21.39407,
      "dividend_per_holder": 168237.2
    },
    {
      "date": "2026-03-30",
      "np": 28.1,
      "expected_np": 18.30665,
      "dividend_per_holder": 391734.0
    },
    {
      "date": "2026-03-31",
      "np": 25.4,
      "expected_np": 15.34445,
      "dividend_per_holder": 402222.0
    },
    {
      "date": "2026-04-02",
      "np": 12.6,
      "expected_np": 17.1503,
      "dividend_per_holder": -182012.2
    },
    {
      "date": "2026-04-05",
      "np": 19.25,
      "expected_np": 19.78566,
      "dividend_per_holder": -21426.4
    },
    {
      "date": "2026-04-07",
      "np": 22.15,
      "expected_np": 18.6652,
      "dividend_per_holder": 139392.2
    },
    {
      "date": "2026-04-08",
      "np": 26.15,
      "expected_np": 21.78537,
      "dividend_per_holder": 174585.4
    }
  ],
  "3202": [
    {
      "date": "2026-03-16",
      "np": 2.6,
      "expected_np": 16.02377,
      "dividend_per_holder": -536950.6
    },
    {
      "date": "2026-03-18",
      "np": 12.65,
      "expected_np": 15.76127,
      "dividend_per_holder": -124450.8
    },
    {
      "date": "2026-03-20",
      "np": 26.05,
      "expected_np": 15.67292,
      "dividend_per_holder": 415083.0
    },
    {
      "date": "2026-03-21",
      "np": 15.9,
      "expected_np": 14.82167,
      "dividend_per_holder": 43133.4
    },
    {
      "date": "2026-03-23",
      "np": 29.2,
      "expected_np": 15.38339,
      "dividend_per_holder": 552664.4
    },
    {
      "date": "2026-03-25",
      "np": 18.1,
      "expected_np": 15.44177,
      "dividend_per_holder": 106329.2
    },
    {
      "date": "2026-03-27",
      "np": 22.4,
      "expected_np": 17.25859,
      "dividend_per_holder": 205656.4
    },
    {
      "date": "2026-03-29",
      "np": 14.0,
      "expected_np": 16.70698,
      "dividend_per_holder": -108279.2
    },
    {
      "date": "2026-03-31",
      "np": 23.2,
      "expected_np": 14.59701,
      "dividend_per_holder": 344119.4
    },
    {
      "date": "2026-04-01",
      "np": 13.55,
      "expected_np": 16.60538,
      "dividend_per_holder": -122215.0
    },
    {
      "date": "2026-04-03",
      "np": 22.0,
      "expected_np": 18.1612,
      "dividend_per_holder": 153552.0
    },
    {
      "date": "2026-04-05",
      "np": 28.15,
      "expected_np": 14.87349,
      "dividend_per_holder": 531060.6
    },
    {
      "date": "2026-04-07",
      "np": 11.95,
      "expected_np": 15.23582,
      "dividend_per_holder": -131432.8
    },
    {
      "date": "2026-04-09",
      "np": 20.3,
      "expected_np": 16.59858,
      "dividend_per_holder": 148056.6
    },
    {
      "date": "2026-04-10",
      "np": 30.3,
      "expected_np": 16.54282,
      "dividend_per_holder": 550287.4
    }
  ],
  "1966": [
    {
      "date": "2026-03-14",
      "np": 9.65,
      "expected_np": 15.35529,
      "dividend_per_holder": -228211.8
    },
    {
      "date": "2026-03-16",
      "np": 15.8,
      "expected_np": 14.03302,
      "dividend_per_holder": 70679.2
    },
    {
      "date": "2026-03-18",
      "np": 27.7,
      "expected_np": 13.63242,
      "dividend_per_holder": 562703.2
    },
    {
      "date": "2026-03-19",
      "np": 19.8,
      "expected_np": 14.47728,
      "dividend_per_holder": 212908.6
    },
    {
      "date": "2026-03-21",
      "np": 9.3,
      "expected_np": 14.85331,
      "dividend_per_holder": -222132.4
    },
    {
      "date": "2026-03-23",
      "np": 9.05,
      "expected_np": 13.24558,
      "dividend_per_holder": -167823.4
    },
    {
      "date": "2026-03-25",
      "np": 22.15,
      "expected_np": 15.8446,
      "dividend_per_holder": 252216.2
    },
    {
      "date": "2026-03-27",
      "np": 10.9,
      "expected_np": 16.28014,
      "dividend_per_holder": -215205.6
    },
    {
      "date": "2026-03-30",
      "np": 18.4,
      "expected_np": 17.7251,
      "dividend_per_holder": 26996.0
    },
    {
      "date": "2026-03-31",
      "np": 11.3,
      "expected_np": 15.28894,
      "dividend_per_holder": -159557.8
    },
    {
      "date": "2026-04-02",
      "np": 9.1,
      "expected_np": 12.42283,
      "dividend_per_holder": -132913.0
    },
    {
      "date": "2026-04-05",
      "np": 26.05,
      "expected_np": 13.94854,
      "dividend_per_holder": 484058.4
    },
    {
      "date": "2026-04-09",
      "np": 26.75,
      "expected_np": 15.22016,
      "dividend_per_holder": 461193.8
    },
    {
      "date": "2026-04-10",
      "np": 32.1,
      "expected_np": 14.82693,
      "dividend_per_holder": 690923.0
    },
    {
      "date": "2026-04-12",
      "np": 14.5,
      "expected_np": 17.38326,
      "dividend_per_holder": -115330.4
    }
  ],
  "4433255": [
    {
      "date": "2026-03-03",
      "np": 8.5,
      "expected_np": 15.40735,
      "dividend_per_holder": -276294.0
    },
    {
      "date": "2026-03-04",
      "np": 18.85,
      "expected_np": 12.21942,
      "dividend_per_holder": 265223.2
    },
    {
      "date": "2026-03-12",
      "np": 9.1,
      "expected_np": 12.34723,
      "dividend_per_holder": -129889.2
    },
    {
      "date": "2026-03-15",
      "np": 24.1,
      "expected_np": 13.18033,
      "dividend_per_holder": 436786.6
    },
    {
      "date": "2026-03-17",
      "np": 16.45,
      "expected_np": 14.22865,
      "dividend_per_holder": 88854.0
    },
    {
      "date": "2026-03-18",
      "np": 5.2,
      "expected_np": 16.01722,
      "dividend_per_holder": -432688.8
    },
    {
      "date": "2026-03-21",
      "np": 17.0,
      "expected_np": 15.13413,
      "dividend_per_holder": 74634.8
    },
    {
      "date": "2026-03-23",
      "np": 19.0,
      "expected_np": 12.62111,
      "dividend_per_holder": 255155.6
    },
    {
      "date": "2026-03-25",
      "np": 3.8,
      "expected_np": 11.98993,
      "dividend_per_holder": -327597.2
    },
    {
      "date": "2026-03-29",
      "np": 12.4,
      "expected_np": 12.27949,
      "dividend_per_holder": 4820.2
    },
    {
      "date": "2026-03-30",
      "np": 11.55,
      "expected_np": 13.44211,
      "dividend_per_holder": -75684.4
    },
    {
      "date": "2026-04-02",
      "np": 6.0,
      "expected_np": 13.39503,
      "dividend_per_holder": -295801.0
    },
    {
      "date": "2026-04-05",
      "np": 21.55,
      "expected_np": 11.86199,
      "dividend_per_holder": 387520.6
    },
    {
      "date": "2026-04-07",
      "np": 14.85,
      "expected_np": 11.6172,
      "dividend_per_holder": 129312.2
    },
    {
      "date": "2026-04-08",
      "np": 36.05,
      "expected_np": 10.3084,
      "dividend_per_holder": 1029664.0
    }
  ],
  "4433134": [
    {
      "date": "2026-03-18",
      "np": 14.1,
      "expected_np": 15.05756,
      "dividend_per_holder": -38302.4
    },
    {
      "date": "2026-03-20",
      "np": 12.8,
      "expected_np": 12.40806,
      "dividend_per_holder": 15677.4
    },
    {
      "date": "2026-03-22",
      "np": 18.1,
      "expected_np": 13.91945,
      "dividend_per_holder": 167222.2
    },
    {
      "date": "2026-03-23",
      "np": 22.55,
      "expected_np": 14.15689,
      "dividend_per_holder": 335724.6
    },
    {
      "date": "2026-03-25",
      "np": 14.05,
      "expected_np": 12.07566,
      "dividend_per_holder": 78973.4
    },
    {
      "date": "2026-03-27",
      "np": 27.4,
      "expected_np": 14.39369,
      "dividend_per_holder": 520252.4
    },
    {
      "date": "2026-03-29",
      "np": 29.5,
      "expected_np": 14.73697,
      "dividend_per_holder": 590521.2
    },
    {
      "date": "2026-03-31",
      "np": 6.5,
      "expected_np": 13.60234,
      "dividend_per_holder": -284093.4
    },
    {
      "date": "2026-04-01",
      "np": 10.6,
      "expected_np": 15.66333,
      "dividend_per_holder": -202533.0
    },
    {
      "date": "2026-04-03",
      "np": 8.2,
      "expected_np": 15.16135,
      "dividend_per_holder": -278453.8
    },
    {
      "date": "2026-04-05",
      "np": 7.05,
      "expected_np": 11.57091,
      "dividend_per_holder": -180836.4
    },
    {
      "date": "2026-04-07",
      "np": 24.2,
      "expected_np": 13.54948,
      "dividend_per_holder": 426020.6
    },
    {
      "date": "2026-04-09",
      "np": 10.15,
      "expected_np": 14.41826,
      "dividend_per_holder": -170730.4
    },
    {
      "date": "2026-04-10",
      "np": 8.45,
      "expected_np": 12.68406,
      "dividend_per_holder": -169362.2
    },
    {
      "date": "2026-04-12",
      "np": 26.6,
      "expected_np": 13.68547,
      "dividend_per_holder": 516581.4
    }
  ],
  "4431678": [
    {
      "date": "2026-02-24",
      "np": 29.0,
      "expected_np": 21.12295,
      "dividend_per_holder": 315081.8
    },
    {
      "date": "2026-02-26",
      "np": 26.7,
      "expected_np": 21.1223,
      "dividend_per_holder": 223108.0
    },
    {
      "date": "2026-03-01",
      "np": 19.6,
      "expected_np": 19.65267,
      "dividend_per_holder": -2106.8
    },
    {
      "date": "2026-03-03",
      "np": 13.35,
      "expected_np": 23.15461,
      "dividend_per_holder": -392184.2
    },
    {
      "date": "2026-03-04",
      "np": 17.5,
      "expected_np": 22.66131,
      "dividend_per_holder": -206452.4
    },
    {
      "date": "2026-03-07",
      "np": 23.35,
      "expected_np": 21.05213,
      "dividend_per_holder": 91914.8
    },
    {
      "date": "2026-03-28",
      "np": 20.75,
      "expected_np": 20.15698,
      "dividend_per_holder": 23720.8
    },
    {
      "date": "2026-03-30",
      "np": 15.45,
      "expected_np": 22.4781,
      "dividend_per_holder": -281124.0
    },
    {
      "date": "2026-04-01",
      "np": 23.15,
      "expected_np": 24.85606,
      "dividend_per_holder": -68242.4
    },
    {
      "date": "2026-04-03",
      "np": 17.9,
      "expected_np": 21.77792,
      "dividend_per_holder": -155117.0
    },
    {
      "date": "2026-04-04",
      "np": 11.8,
      "expected_np": 19.04439,
      "dividend_per_holder": -289775.4
    },
    {
      "date": "2026-04-06",
      "np": 4.8,
      "expected_np": 17.65196,
      "dividend_per_holder": -514078.4
    },
    {
      "date": "2026-04-09",
      "np": 14.15,
      "expected_np": 17.62704,
      "dividend_per_holder": -139081.8
    },
    {
      "date": "2026-04-10",
      "np": 22.55,
      "expected_np": 19.34997,
      "dividend_per_holder": 128001.2
    },
    {
      "date": "2026-04-12",
      "np": 13.2,
      "expected_np": 20.6908,
      "dividend_per_holder": -299631.8
    }
  ],
  "3059318": [
    {
      "date": "2026-01-22",
      "np": 28.55,
      "expected_np": 18.82244,
      "dividend_per_holder": 389102.4
    },
    {
      "date": "2026-01-24",
      "np": 30.85,
      "expected_np": 21.44609,
      "dividend_per_holder": 376156.6
    },
    {
      "date": "2026-01-27",
      "np": 23.55,
      "expected_np": 22.29225,
      "dividend_per_holder": 50310.0
    },
    {
      "date": "2026-01-29",
      "np": 32.4,
      "expected_np": 22.37309,
      "dividend_per_holder": 401076.4
    },
    {
      "date": "2026-01-31",
      "np": 29.4,
      "expected_np": 23.39026,
      "dividend_per_holder": 240389.4
    },
    {
      "date": "2026-02-02",
      "np": 15.6,
      "expected_np": 22.50399,
      "dividend_per_holder": -276159.6
    },
    {
      "date": "2026-02-05",
      "np": 32.85,
      "expected_np": 21.84453,
      "dividend_per_holder": 440218.6
    },
    {
      "date": "2026-02-07",
      "np": 24.5,
      "expected_np": 21.96112,
      "dividend_per_holder": 101555.0
    },
    {
      "date": "2026-02-24",
      "np": 21.1,
      "expected_np": 22.89751,
      "dividend_per_holder": -71900.4
    },
    {
      "date": "2026-02-26",
      "np": 18.45,
      "expected_np": 20.85979,
      "dividend_per_holder": -96391.6
    },
    {
      "date": "2026-03-25",
      "np": 31.75,
      "expected_np": 21.99838,
      "dividend_per_holder": 390064.6
    },
    {
      "date": "2026-03-28",
      "np": 19.9,
      "expected_np": 15.29722,
      "dividend_per_holder": 184111.0
    },
    {
      "date": "2026-03-30",
      "np": 12.5,
      "expected_np": 21.83132,
      "dividend_per_holder": -373252.6
    },
    {
      "date": "2026-04-03",
      "np": 17.2,
      "expected_np": 22.17557,
      "dividend_per_holder": -199023.0
    },
    {
      "date": "2026-04-06",
      "np": 25.45,
      "expected_np": 20.37186,
      "dividend_per_holder": 203125.4
    }
  ],
  "4432816": [
    {
      "date": "2026-03-14",
      "np": 15.8,
      "expected_np": 13.17499,
      "dividend_per_holder": 105000.6
    },
    {
      "date": "2026-03-17",
      "np": 24.55,
      "expected_np": 13.59342,
      "dividend_per_holder": 438263.2
    },
    {
      "date": "2026-03-19",
      "np": 21.3,
      "expected_np": 16.27328,
      "dividend_per_holder": 201068.8
    },
    {
      "date": "2026-03-21",
      "np": 23.85,
      "expected_np": 15.10867,
      "dividend_per_holder": 349653.2
    },
    {
      "date": "2026-03-24",
      "np": 21.0,
      "expected_np": 16.36175,
      "dividend_per_holder": 185530.0
    },
    {
      "date": "2026-03-26",
      "np": 16.35,
      "expected_np": 13.98407,
      "dividend_per_holder": 94637.2
    },
    {
      "date": "2026-03-28",
      "np": 7.15,
      "expected_np": 16.61533,
      "dividend_per_holder": -378613.2
    },
    {
      "date": "2026-03-29",
      "np": 8.0,
      "expected_np": 16.22312,
      "dividend_per_holder": -328925.0
    },
    {
      "date": "2026-03-31",
      "np": 9.0,
      "expected_np": 16.1419,
      "dividend_per_holder": -285676.0
    },
    {
      "date": "2026-04-02",
      "np": 16.05,
      "expected_np": 15.49345,
      "dividend_per_holder": 22261.8
    },
    {
      "date": "2026-04-03",
      "np": 15.2,
      "expected_np": 16.63091,
      "dividend_per_holder": -57236.4
    },
    {
      "date": "2026-04-05",
      "np": 28.05,
      "expected_np": 13.9008,
      "dividend_per_holder": 565968.0
    },
    {
      "date": "2026-04-07",
      "np": 25.5,
      "expected_np": 14.03992,
      "dividend_per_holder": 458403.0
    },
    {
      "date": "2026-04-10",
      "np": 21.05,
      "expected_np": 15.68605,
      "dividend_per_holder": 214558.2
    },
    {
      "date": "2026-04-12",
      "np": 12.05,
      "expected_np": 15.35872,
      "dividend_per_holder": -132349.0
    }
  ],
  "3917376": [
    {
      "date": "2026-03-08",
      "np": 15.35,
      "expected_np": 18.63633,
      "dividend_per_holder": -131453.2
    },
    {
      "date": "2026-03-10",
      "np": 7.95,
      "expected_np": 18.45205,
      "dividend_per_holder": -420082.0
    },
    {
      "date": "2026-03-12",
      "np": 21.95,
      "expected_np": 14.55508,
      "dividend_per_holder": 295796.8
    },
    {
      "date": "2026-03-14",
      "np": 8.8,
      "expected_np": 21.1198,
      "dividend_per_holder": -492792.2
    },
    {
      "date": "2026-03-16",
      "np": 32.35,
      "expected_np": 17.55959,
      "dividend_per_holder": 591616.4
    },
    {
      "date": "2026-03-18",
      "np": 24.45,
      "expected_np": 19.67909,
      "dividend_per_holder": 190836.4
    },
    {
      "date": "2026-03-20",
      "np": 20.95,
      "expected_np": 20.18178,
      "dividend_per_holder": 30728.8
    },
    {
      "date": "2026-03-22",
      "np": 12.85,
      "expected_np": 20.54431,
      "dividend_per_holder": -307772.4
    },
    {
      "date": "2026-03-25",
      "np": 25.5,
      "expected_np": 18.79697,
      "dividend_per_holder": 268121.0
    },
    {
      "date": "2026-03-30",
      "np": 11.65,
      "expected_np": 20.58011,
      "dividend_per_holder": -357204.2
    },
    {
      "date": "2026-04-01",
      "np": 33.35,
      "expected_np": 22.08927,
      "dividend_per_holder": 450429.0
    },
    {
      "date": "2026-04-03",
      "np": 18.8,
      "expected_np": 22.70586,
      "dividend_per_holder": -156234.6
    },
    {
      "date": "2026-04-05",
      "np": 16.7,
      "expected_np": 20.1392,
      "dividend_per_holder": -137568.0
    },
    {
      "date": "2026-04-07",
      "np": 19.05,
      "expected_np": 19.71114,
      "dividend_per_holder": -26445.4
    },
    {
      "date": "2026-04-10",
      "np": 10.5,
      "expected_np": 23.13854,
      "dividend_per_holder": -505541.6
    }
  ],
  "4251": [
    {
      "date": "2026-01-16",
      "np": 11.9,
      "expected_np": 11.35182,
      "dividend_per_holder": 21927.0
    },
    {
      "date": "2026-01-22",
      "np": 10.0,
      "expected_np": 9.61933,
      "dividend_per_holder": 15226.8
    },
    {
      "date": "2026-01-24",
      "np": 4.75,
      "expected_np": 10.84554,
      "dividend_per_holder": -243821.6
    },
    {
      "date": "2026-01-27",
      "np": 26.8,
      "expected_np": 11.12482,
      "dividend_per_holder": 627007.2
    },
    {
      "date": "2026-01-29",
      "np": 10.0,
      "expected_np": 12.64615,
      "dividend_per_holder": -105846.2
    },
    {
      "date": "2026-03-25",
      "np": 28.75,
      "expected_np": 12.70597,
      "dividend_per_holder": 641761.0
    },
    {
      "date": "2026-03-28",
      "np": 22.75,
      "expected_np": 8.71401,
      "dividend_per_holder": 561439.6
    },
    {
      "date": "2026-03-30",
      "np": 9.4,
      "expected_np": 12.84181,
      "dividend_per_holder": -137672.4
    },
    {
      "date": "2026-04-01",
      "np": 39.4,
      "expected_np": 14.21972,
      "dividend_per_holder": 1007211.2
    },
    {
      "date": "2026-04-03",
      "np": 17.55,
      "expected_np": 13.47271,
      "dividend_per_holder": 163091.6
    },
    {
      "date": "2026-04-04",
      "np": 15.25,
      "expected_np": 13.15785,
      "dividend_per_holder": 83686.2
    },
    {
      "date": "2026-04-06",
      "np": 8.65,
      "expected_np": 11.86032,
      "dividend_per_holder": -128413.0
    },
    {
      "date": "2026-04-09",
      "np": -2.05,
      "expected_np": 12.16248,
      "dividend_per_holder": -568499.0
    },
    {
      "date": "2026-04-10",
      "np": 11.9,
      "expected_np": 12.46825,
      "dividend_per_holder": -22730.2
    },
    {
      "date": "2026-04-12",
      "np": 7.55,
      "expected_np": 13.25839,
      "dividend_per_holder": -228335.6
    }
  ],
  "4066336": [
    {
      "date": "2025-12-30",
      "np": 17.7,
      "expected_np": 17.65132,
      "dividend_per_holder": 1947.4
    },
    {
      "date": "2026-01-03",
      "np": 22.15,
      "expected_np": 18.01786,
      "dividend_per_holder": 165285.8
    },
    {
      "date": "2026-01-05",
      "np": 15.85,
      "expected_np": 19.67821,
      "dividend_per_holder": -153128.4
    },
    {
      "date": "2026-01-07",
      "np": 20.05,
      "expected_np": 15.63468,
      "dividend_per_holder": 176612.6
    },
    {
      "date": "2026-01-08",
      "np": 22.3,
      "expected_np": 19.07878,
      "dividend_per_holder": 128849.0
    },
    {
      "date": "2026-01-12",
      "np": 22.2,
      "expected_np": 18.81007,
      "dividend_per_holder": 135597.0
    },
    {
      "date": "2026-01-27",
      "np": 12.35,
      "expected_np": 18.6929,
      "dividend_per_holder": -253715.8
    },
    {
      "date": "2026-01-28",
      "np": 12.55,
      "expected_np": 16.81727,
      "dividend_per_holder": -170690.8
    },
    {
      "date": "2026-02-01",
      "np": 21.4,
      "expected_np": 16.09514,
      "dividend_per_holder": 212194.2
    },
    {
      "date": "2026-02-03",
      "np": 17.4,
      "expected_np": 18.88602,
      "dividend_per_holder": -59440.8
    },
    {
      "date": "2026-02-05",
      "np": 13.9,
      "expected_np": 17.12551,
      "dividend_per_holder": -129020.4
    },
    {
      "date": "2026-02-07",
      "np": 18.65,
      "expected_np": 10.43044,
      "dividend_per_holder": 328782.4
    },
    {
      "date": "2026-02-09",
      "np": 9.75,
      "expected_np": 14.69037,
      "dividend_per_holder": -197614.8
    },
    {
      "date": "2026-02-11",
      "np": 17.75,
      "expected_np": 15.15821,
      "dividend_per_holder": 103671.8
    },
    {
      "date": "2026-02-23",
      "np": 18.8,
      "expected_np": 11.77542,
      "dividend_per_holder": 280983.2
    }
  ],
  "4222252": [
    {
      "date": "2026-02-24",
      "np": 11.2,
      "expected_np": 9.64253,
      "dividend_per_holder": 62299.0
    },
    {
      "date": "2026-02-27",
      "np": 15.55,
      "expected_np": 8.78145,
      "dividend_per_holder": 270741.8
    },
    {
      "date": "2026-03-01",
      "np": 6.7,
      "expected_np": 9.6872,
      "dividend_per_holder": -119488.0
    },
    {
      "date": "2026-03-04",
      "np": -0.65,
      "expected_np": 8.46725,
      "dividend_per_holder": -364690.0
    },
    {
      "date": "2026-03-15",
      "np": 3.05,
      "expected_np": 7.78401,
      "dividend_per_holder": -189360.4
    },
    {
      "date": "2026-03-17",
      "np": 3.9,
      "expected_np": 8.05328,
      "dividend_per_holder": -166131.4
    },
    {
      "date": "2026-03-21",
      "np": 18.75,
      "expected_np": 8.46272,
      "dividend_per_holder": 411491.2
    },
    {
      "date": "2026-03-23",
      "np": 13.85,
      "expected_np": 8.00727,
      "dividend_per_holder": 233709.0
    },
    {
      "date": "2026-03-25",
      "np": 8.0,
      "expected_np": 7.4755,
      "dividend_per_holder": 20980.0
    },
    {
      "date": "2026-03-27",
      "np": 8.8,
      "expected_np": 10.42719,
      "dividend_per_holder": -65087.8
    },
    {
      "date": "2026-03-29",
      "np": 6.4,
      "expected_np": 8.86388,
      "dividend_per_holder": -98555.2
    },
    {
      "date": "2026-04-02",
      "np": 12.7,
      "expected_np": 9.84339,
      "dividend_per_holder": 114264.2
    },
    {
      "date": "2026-04-05",
      "np": 11.75,
      "expected_np": 9.84717,
      "dividend_per_holder": 76113.0
    },
    {
      "date": "2026-04-07",
      "np": 1.6,
      "expected_np": 9.14522,
      "dividend_per_holder": -301809.0
    },
    {
      "date": "2026-04-08",
      "np": 10.9,
      "expected_np": 6.01163,
      "dividend_per_holder": 195534.8
    }
  ],
  "4566434": [
    {
      "date": "2025-11-28",
      "np": 14.85,
      "expected_np": 14.87887,
      "dividend_per_holder": -1154.8
    },
    {
      "date": "2025-12-01",
      "np": 17.8,
      "expected_np": 18.07271,
      "dividend_per_holder": -10908.4
    },
    {
      "date": "2025-12-03",
      "np": 23.05,
      "expected_np": 17.10217,
      "dividend_per_holder": 237913.2
    },
    {
      "date": "2025-12-05",
      "np": 22.15,
      "expected_np": 18.17931,
      "dividend_per_holder": 158827.6
    },
    {
      "date": "2025-12-07",
      "np": 8.4,
      "expected_np": 16.6001,
      "dividend_per_holder": -328004.0
    },
    {
      "date": "2026-01-15",
      "np": 8.75,
      "expected_np": 10.7629,
      "dividend_per_holder": -80515.8
    },
    {
      "date": "2026-01-18",
      "np": 8.1,
      "expected_np": 12.73609,
      "dividend_per_holder": -185443.6
    },
    {
      "date": "2026-02-09",
      "np": 11.75,
      "expected_np": 12.91072,
      "dividend_per_holder": -46428.6
    },
    {
      "date": "2026-02-11",
      "np": 2.6,
      "expected_np": 11.0018,
      "dividend_per_holder": -336072.0
    },
    {
      "date": "2026-04-01",
      "np": 3.4,
      "expected_np": 9.98102,
      "dividend_per_holder": -263241.0
    },
    {
      "date": "2026-04-03",
      "np": 12.9,
      "expected_np": 10.44821,
      "dividend_per_holder": 98071.6
    },
    {
      "date": "2026-04-05",
      "np": 7.25,
      "expected_np": 10.49112,
      "dividend_per_holder": -129645.0
    },
    {
      "date": "2026-04-08",
      "np": 9.9,
      "expected_np": 10.26157,
      "dividend_per_holder": -14463.0
    },
    {
      "date": "2026-04-10",
      "np": 17.7,
      "expected_np": 11.36155,
      "dividend_per_holder": 253537.8
    },
    {
      "date": "2026-04-12",
      "np": 11.05,
      "expected_np": 10.24243,
      "dividend_per_holder": 32303.0
    }
  ],
  "3936299": [
    {
      "date": "2026-03-11",
      "np": 21.95,
      "expected_np": 16.93126,
      "dividend_per_holder": 200749.6
    },
    {
      "date": "2026-03-12",
      "np": 28.9,
      "expected_np": 16.07543,
      "dividend_per_holder": 512982.6
    },
    {
      "date": "2026-03-14",
      "np": -2.75,
      "expected_np": 18.67113,
      "dividend_per_holder": -856845.4
    },
    {
      "date": "2026-03-17",
      "np": 7.85,
      "expected_np": 18.25373,
      "dividend_per_holder": -416149.4
    },
    {
      "date": "2026-03-18",
      "np": 17.65,
      "expected_np": 16.43645,
      "dividend_per_holder": 48541.8
    },
    {
      "date": "2026-03-20",
      "np": 25.1,
      "expected_np": 17.20533,
      "dividend_per_holder": 315786.8
    },
    {
      "date": "2026-03-22",
      "np": 16.0,
      "expected_np": 18.76753,
      "dividend_per_holder": -110701.0
    },
    {
      "date": "2026-03-24",
      "np": 10.95,
      "expected_np": 16.03865,
      "dividend_per_holder": -203545.8
    },
    {
      "date": "2026-03-25",
      "np": 42.15,
      "expected_np": 18.40123,
      "dividend_per_holder": 949951.0
    },
    {
      "date": "2026-03-27",
      "np": 29.45,
      "expected_np": 21.05924,
      "dividend_per_holder": 335630.6
    },
    {
      "date": "2026-03-29",
      "np": 17.7,
      "expected_np": 19.58319,
      "dividend_per_holder": -75327.8
    },
    {
      "date": "2026-04-01",
      "np": 30.15,
      "expected_np": 19.53519,
      "dividend_per_holder": 424592.2
    },
    {
      "date": "2026-04-04",
      "np": 10.85,
      "expected_np": 17.9704,
      "dividend_per_holder": -284816.2
    },
    {
      "date": "2026-04-06",
      "np": 14.85,
      "expected_np": 19.18188,
      "dividend_per_holder": -173275.2
    },
    {
      "date": "2026-04-08",
      "np": 17.05,
      "expected_np": 18.54467,
      "dividend_per_holder": -59787.0
    }
  ],
  "6430": [
    {
      "date": "2025-12-18",
      "np": 24.25,
      "expected_np": 16.57452,
      "dividend_per_holder": 307019.2
    },
    {
      "date": "2025-12-20",
      "np": 14.05,
      "expected_np": 17.15728,
      "dividend_per_holder": -124291.0
    },
    {
      "date": "2025-12-22",
      "np": 19.25,
      "expected_np": 16.97466,
      "dividend_per_holder": 91013.6
    },
    {
      "date": "2025-12-25",
      "np": 12.55,
      "expected_np": 16.54521,
      "dividend_per_holder": -159808.6
    },
    {
      "date": "2025-12-28",
      "np": 9.6,
      "expected_np": 15.85413,
      "dividend_per_holder": -250165.0
    },
    {
      "date": "2025-12-29",
      "np": 19.15,
      "expected_np": 16.19673,
      "dividend_per_holder": 118131.0
    },
    {
      "date": "2025-12-31",
      "np": 16.4,
      "expected_np": 15.99463,
      "dividend_per_holder": 16215.0
    },
    {
      "date": "2026-01-03",
      "np": 14.3,
      "expected_np": 17.02263,
      "dividend_per_holder": -108905.2
    },
    {
      "date": "2026-01-05",
      "np": 22.05,
      "expected_np": 15.03254,
      "dividend_per_holder": 280698.4
    },
    {
      "date": "2026-01-07",
      "np": 13.25,
      "expected_np": 16.53334,
      "dividend_per_holder": -131333.4
    },
    {
      "date": "2026-01-09",
      "np": 14.3,
      "expected_np": 17.31461,
      "dividend_per_holder": -120584.2
    },
    {
      "date": "2026-01-11",
      "np": 26.6,
      "expected_np": 15.20076,
      "dividend_per_holder": 455969.6
    },
    {
      "date": "2026-01-13",
      "np": 16.0,
      "expected_np": 16.69917,
      "dividend_per_holder": -27966.8
    },
    {
      "date": "2026-01-15",
      "np": 31.75,
      "expected_np": 15.61425,
      "dividend_per_holder": 645429.8
    },
    {
      "date": "2026-01-19",
      "np": 15.8,
      "expected_np": 17.09053,
      "dividend_per_holder": -51621.0
    }
  ],
  "3934719": [
    {
      "date": "2026-03-11",
      "np": 20.0,
      "expected_np": 13.20087,
      "dividend_per_holder": 271965.4
    },
    {
      "date": "2026-03-13",
      "np": 17.8,
      "expected_np": 12.46357,
      "dividend_per_holder": 213457.2
    },
    {
      "date": "2026-03-15",
      "np": 9.65,
      "expected_np": 12.357,
      "dividend_per_holder": -108280.0
    },
    {
      "date": "2026-03-17",
      "np": 25.8,
      "expected_np": 12.7683,
      "dividend_per_holder": 521267.8
    },
    {
      "date": "2026-03-20",
      "np": 7.55,
      "expected_np": 11.72286,
      "dividend_per_holder": -166914.2
    },
    {
      "date": "2026-03-22",
      "np": -1.6,
      "expected_np": 13.72737,
      "dividend_per_holder": -613094.8
    },
    {
      "date": "2026-03-24",
      "np": 18.05,
      "expected_np": 11.84118,
      "dividend_per_holder": 248352.6
    },
    {
      "date": "2026-03-26",
      "np": 10.1,
      "expected_np": 11.00196,
      "dividend_per_holder": -36078.2
    },
    {
      "date": "2026-03-29",
      "np": 2.6,
      "expected_np": 9.97452,
      "dividend_per_holder": -294980.6
    },
    {
      "date": "2026-03-31",
      "np": 4.1,
      "expected_np": 9.73772,
      "dividend_per_holder": -225509.0
    },
    {
      "date": "2026-04-01",
      "np": 22.0,
      "expected_np": 10.9819,
      "dividend_per_holder": 440723.8
    },
    {
      "date": "2026-04-03",
      "np": 26.15,
      "expected_np": 12.75455,
      "dividend_per_holder": 535818.2
    },
    {
      "date": "2026-04-06",
      "np": 13.45,
      "expected_np": 10.94442,
      "dividend_per_holder": 100223.4
    },
    {
      "date": "2026-04-09",
      "np": 7.25,
      "expected_np": 10.64421,
      "dividend_per_holder": -135768.6
    },
    {
      "date": "2026-04-10",
      "np": 1.1,
      "expected_np": 11.25616,
      "dividend_per_holder": -406246.6
    }
  ],
  "3934672": [
    {
      "date": "2026-03-08",
      "np": 8.8,
      "expected_np": 16.71752,
      "dividend_per_holder": -316700.8
    },
    {
      "date": "2026-03-09",
      "np": 19.35,
      "expected_np": 16.74761,
      "dividend_per_holder": 104095.4
    },
    {
      "date": "2026-03-11",
      "np": 25.1,
      "expected_np": 19.45429,
      "dividend_per_holder": 225828.4
    },
    {
      "date": "2026-03-13",
      "np": 20.4,
      "expected_np": 18.58629,
      "dividend_per_holder": 72548.4
    },
    {
      "date": "2026-03-15",
      "np": 24.35,
      "expected_np": 18.07423,
      "dividend_per_holder": 251030.8
    },
    {
      "date": "2026-03-20",
      "np": 8.55,
      "expected_np": 18.5017,
      "dividend_per_holder": -398067.8
    },
    {
      "date": "2026-03-22",
      "np": 14.05,
      "expected_np": 21.46904,
      "dividend_per_holder": -296761.6
    },
    {
      "date": "2026-03-24",
      "np": 23.35,
      "expected_np": 18.38374,
      "dividend_per_holder": 198650.4
    },
    {
      "date": "2026-03-26",
      "np": 19.8,
      "expected_np": 16.58274,
      "dividend_per_holder": 128690.4
    },
    {
      "date": "2026-03-29",
      "np": 20.8,
      "expected_np": 16.2152,
      "dividend_per_holder": 183392.2
    },
    {
      "date": "2026-03-31",
      "np": 5.9,
      "expected_np": 16.74775,
      "dividend_per_holder": -433910.0
    },
    {
      "date": "2026-04-03",
      "np": 12.8,
      "expected_np": 19.22477,
      "dividend_per_holder": -256990.6
    },
    {
      "date": "2026-04-06",
      "np": 22.75,
      "expected_np": 15.95861,
      "dividend_per_holder": 271655.6
    },
    {
      "date": "2026-04-09",
      "np": 18.9,
      "expected_np": 16.56499,
      "dividend_per_holder": 93400.6
    },
    {
      "date": "2026-04-10",
      "np": 22.4,
      "expected_np": 17.70362,
      "dividend_per_holder": 187855.4
    }
  ]
};

// A stable source-data spot check retained alongside the rolling last-15 series.
export const trendSpotChecks: Record<string, Record<string, TrendPoint>> = {
  "3112335": {
    "2025-12-25": {
      "date": "2025-12-25",
      "np": 59.35,
      "expected_np": 25.54725,
      "dividend_per_holder": 1352109.8
    }
  }
};
